name: Verify Memory Tests

on:
  push:
    paths:
      - 'assignments/memory/**'
  pull_request:
    paths:
      - 'assignments/memory/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build C file
      run: make -C assignments/memory/

    - name: Run Tests
      run: assignments/memory/test_filter

    - name: Verify
      run: exit $?
